/** Universities: home institution first, then A–Z, Other last. */
export const UNIVERSITIES = [
  "University of Jeddah",
  "Al Baha University",
  "Al Jouf University",
  "Al Yamamah University",
  "Alfaisal University",
  "AlMaarefa University",
  "Arab Open University",
  "Dar Al Uloom University",
  "Dar Al-Hekma University",
  "Effat University",
  "Fahd bin Sultan University",
  "Imam Abdulrahman Bin Faisal University",
  "Imam Mohammad Ibn Saud Islamic University",
  "Islamic University of Medina",
  "Jazan University",
  "King Abdulaziz University",
  "King Abdullah University of Science and Technology",
  "King Fahd University of Petroleum and Minerals",
  "King Faisal University",
  "King Khalid University",
  "King Saud bin Abdulaziz University for Health Sciences",
  "King Saud University",
  "Majmaah University",
  "Najran University",
  "Northern Border University",
  "Prince Mohammad University",
  "Prince Mugrin University",
  "Prince Sattam Bin Abdulaziz University",
  "Prince Sultan University",
  "Princess Nourah Bint Abdulrahman University",
  "Qassim University",
  "Saudi Electronic University",
  "Shaqra University",
  "Sulaiman Al Rajhi University",
  "Taibah University",
  "Taif University",
  "Umm Al-Qura University",
  "University of Bisha",
  "University of Business and Technology",
  "University of Hafr Al Batin",
  "University of Hail",
  "University of Tabuk",
  "Other",
];

/** Majors grouped for the profile completion dropdown. */
export const MAJOR_GROUPS = [
  {
    label: "Computing & AI",
    options: [
      "Artificial Intelligence",
      "Computer Science",
      "Cybersecurity",
      "Data Science",
      "Information Systems",
      "Information Technology",
      "Machine Learning",
      "Software Engineering",
    ],
  },
  {
    label: "Engineering & Sciences",
    options: [
      "Computer Engineering",
      "Electrical Engineering",
      "Engineering",
      "Mathematics",
      "Physics",
      "Statistics",
    ],
  },
  {
    label: "Other Fields",
    options: ["Business", "Economics", "Other"],
  },
];
